import type { ImageSourcePropType } from 'react-native';
import type { RouteId } from './dataset';

// Auto-generated by scripts/fetch-images.sh once you've downloaded the
// Wikimedia Commons photos to src/assets/routes/. Until then, every
// entry is undefined and the app falls back to the tint colour.
export const ROUTE_IMAGES: Partial<Record<RouteId, ImageSourcePropType>> = {};
