#!/usr/bin/env bash
# scripts/fetch-images.sh
#
# Downloads Wikimedia Commons photographs for each element + route into
# src/assets/{elements,routes}/, then writes the typed registries
# (src/features/{elements,routes}/images.ts) so dataset.ts can resolve
# each image via require().
#
# Run from anywhere; the script cds to repo root.
#
# Re-runnable. Existing files are overwritten. If a URL 404s, the
# script aborts and tells you which file. Edit the URL below and re-run.
set -euo pipefail

cd "$(dirname "$0")/.."

ELEMENTS_DIR="src/assets/elements"
ROUTES_DIR="src/assets/routes"
ELEMENTS_REG="src/features/elements/images.ts"
ROUTES_REG="src/features/routes/images.ts"

mkdir -p "$ELEMENTS_DIR" "$ROUTES_DIR"

# Each entry: <output-path>|<wikimedia-commons-thumb-url>
# URLs target 800px-wide thumbnails of public Wikimedia Commons files.
# If a URL fails, replace it with another Commons image and re-run.
ENTRIES=(
  "$ELEMENTS_DIR/boudha.jpg|https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Bodhnath_stupa.jpg/800px-Bodhnath_stupa.jpg"
  "$ELEMENTS_DIR/pashupatinath.jpg|https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Pashupatinath_Temple%2C_Kathmandu%2C_Nepal.jpg/800px-Pashupatinath_Temple%2C_Kathmandu%2C_Nepal.jpg"
  "$ELEMENTS_DIR/swayambhu.jpg|https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Swayambhunath-eyes.jpg/800px-Swayambhunath-eyes.jpg"
  "$ELEMENTS_DIR/lionGate.jpg|https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Lion_at_Bhaktapur_Durbar_Square.jpg/800px-Lion_at_Bhaktapur_Durbar_Square.jpg"
  "$ELEMENTS_DIR/lotusMotif.jpg|https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Lotus_carving_in_Patan.jpg/800px-Lotus_carving_in_Patan.jpg"
  "$ELEMENTS_DIR/patanDurbar.jpg|https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Patan_Durbar_Square_2017.jpg/800px-Patan_Durbar_Square_2017.jpg"
  "$ELEMENTS_DIR/bhaktapurDurbar.jpg|https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Bhaktapur_Durbar_Square_2019.jpg/800px-Bhaktapur_Durbar_Square_2019.jpg"
  "$ELEMENTS_DIR/newariWindow.jpg|https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Peacock_Window_Bhaktapur.jpg/800px-Peacock_Window_Bhaktapur.jpg"
  "$ELEMENTS_DIR/torana.jpg|https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Golden_Gate_Bhaktapur_torana.jpg/800px-Golden_Gate_Bhaktapur_torana.jpg"
  "$ELEMENTS_DIR/prayerWheel.jpg|https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Prayer_wheels_at_Boudhanath.jpg/800px-Prayer_wheels_at_Boudhanath.jpg"
  "$ELEMENTS_DIR/bell.jpg|https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Temple_bell_Nepal.jpg/800px-Temple_bell_Nepal.jpg"
  "$ELEMENTS_DIR/diyo.jpg|https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Diya_lamp.jpg/800px-Diya_lamp.jpg"
  "$ROUTES_DIR/patanDawn.jpg|https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Patan_Durbar_Square_dawn.jpg/800px-Patan_Durbar_Square_dawn.jpg"
  "$ROUTES_DIR/boudhaKora.jpg|https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Boudhanath_kora_walkway.jpg/800px-Boudhanath_kora_walkway.jpg"
  "$ROUTES_DIR/swayambhuClimb.jpg|https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Swayambhunath_stairs.jpg/800px-Swayambhunath_stairs.jpg"
)

echo "Fetching ${#ENTRIES[@]} images…"
for entry in "${ENTRIES[@]}"; do
  out="${entry%|*}"
  url="${entry##*|}"
  echo "  → $out"
  if ! curl -fsSL -o "$out" -H "User-Agent: kathmandu-lens/0.1 (https://github.com/sarozz/lensnepal)" "$url"; then
    echo ""
    echo "ERROR: failed to fetch $url"
    echo "       The Commons file may have moved or been removed."
    echo "       Find a replacement on https://commons.wikimedia.org and edit this script."
    exit 1
  fi
done

echo ""
echo "Writing $ELEMENTS_REG…"
cat > "$ELEMENTS_REG" <<'EOF'
import type { ImageSourcePropType } from 'react-native';
import type { ElementId } from './dataset';

// Generated by scripts/fetch-images.sh. Run that script to refresh.
// Keep this file in version control so the wiring survives re-installs.
export const ELEMENT_IMAGES: Partial<Record<ElementId, ImageSourcePropType>> = {
  boudha: require('@/assets/elements/boudha.jpg'),
  pashupatinath: require('@/assets/elements/pashupatinath.jpg'),
  swayambhu: require('@/assets/elements/swayambhu.jpg'),
  lionGate: require('@/assets/elements/lionGate.jpg'),
  lotusMotif: require('@/assets/elements/lotusMotif.jpg'),
  patanDurbar: require('@/assets/elements/patanDurbar.jpg'),
  bhaktapurDurbar: require('@/assets/elements/bhaktapurDurbar.jpg'),
  newariWindow: require('@/assets/elements/newariWindow.jpg'),
  torana: require('@/assets/elements/torana.jpg'),
  prayerWheel: require('@/assets/elements/prayerWheel.jpg'),
  bell: require('@/assets/elements/bell.jpg'),
  diyo: require('@/assets/elements/diyo.jpg'),
};
EOF

echo "Writing $ROUTES_REG…"
cat > "$ROUTES_REG" <<'EOF'
import type { ImageSourcePropType } from 'react-native';
import type { RouteId } from './dataset';

// Generated by scripts/fetch-images.sh. Run that script to refresh.
// Keep this file in version control so the wiring survives re-installs.
export const ROUTE_IMAGES: Partial<Record<RouteId, ImageSourcePropType>> = {
  patanDawn: require('@/assets/routes/patanDawn.jpg'),
  boudhaKora: require('@/assets/routes/boudhaKora.jpg'),
  swayambhuClimb: require('@/assets/routes/swayambhuClimb.jpg'),
};
EOF

echo ""
echo "Done. Restart pnpm dev to pick up the new images."
echo "Attribution lives in CREDITS.md — keep it accurate when you swap images."
