import type { ImageSourcePropType } from 'react-native';
import type { ElementId } from './dataset';

// Auto-generated by scripts/fetch-images.sh once you've downloaded the
// Wikimedia Commons photos to src/assets/elements/. Until then, every
// entry is undefined and the app falls back to the tint colour.
export const ELEMENT_IMAGES: Partial<Record<ElementId, ImageSourcePropType>> = {};
